/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTenantSlugRouteImport } from './routes/_app.$tenantSlug'
import { Route as AppTenantSlugIndexRouteImport } from './routes/_app.$tenantSlug.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantSlugRoute = AppTenantSlugRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantSlugIndexRoute = AppTenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$tenantSlug': typeof AppTenantSlugRouteWithChildren
  '/$tenantSlug/': typeof AppTenantSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$tenantSlug': typeof AppTenantSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$tenantSlug': typeof AppTenantSlugRouteWithChildren
  '/_app/$tenantSlug/': typeof AppTenantSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/$tenantSlug' | '/$tenantSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$tenantSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/$tenantSlug'
    | '/_app/$tenantSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$tenantSlug': {
      id: '/_app/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof AppTenantSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$tenantSlug/': {
      id: '/_app/$tenantSlug/'
      path: '/'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof AppTenantSlugIndexRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
  }
}

interface AppTenantSlugRouteChildren {
  AppTenantSlugIndexRoute: typeof AppTenantSlugIndexRoute
}

const AppTenantSlugRouteChildren: AppTenantSlugRouteChildren = {
  AppTenantSlugIndexRoute: AppTenantSlugIndexRoute,
}

const AppTenantSlugRouteWithChildren = AppTenantSlugRoute._addFileChildren(
  AppTenantSlugRouteChildren,
)

interface AppRouteChildren {
  AppTenantSlugRoute: typeof AppTenantSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppTenantSlugRoute: AppTenantSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
